#!/bin/bash
cd `dirname $0`
source inc/common.bash

statusecho "Starting your local PostgreSQL server"
pg_ctl -D $PG_DIR -l $PG_DIR/postgresql.log start || die "Failed to start the local PostgreSQL server. Is it already running? Have you run setup-localpostgres yet?"
