#!/bin/bash
cd `dirname $0`
source inc/common.bash

statusecho "Stopping your local lighttpd HTTP server"
kill `cat $HOME/geovision-lighttpd/lighttpd.pid` > /dev/null 2>&1
kill `cat $HOME/geovision-lighttpd/django.pid` > /dev/null 2>&1
